#!/bin/bash
if ! tmux has-session -t home; then
  tmux new -s home -d

  tmux rename-window -t home:1 🏡
  tmux send-keys -t home:1 \
    cd Space ~ Enter
  
  if [ -z $TMUX ]; then
    tmux a -t home:1
  else
    tmux switch -t home:1
  fi
else
  if [ -z $TMUX ]; then
    tmux a -t home -c ~
  else
    tmux switch -t home
  fi
fi
